#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 20, 2018 01:38:17 PM +0200  platform: Windows NT

import sys
from tkinter.filedialog import askdirectory

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global corpusTextField
    corpusTextField = tk.Entry()
    corpusTextField.insert(0,"")
    global postingTextField
    postingTextField = tk.Entry()
    global generateButton
    generateButton = tk.StringVar()
    generateButton.set('Generate Engine')
    global multiQueryTextField
    multiQueryTextField = tk.Entry()
    global singleQuertTextField
    singleQuertTextField = tk.Entry()
    global citiesOnlyResV
    citiesOnlyResV = tk.IntVar()
    global semanticV
    semanticV = tk.IntVar()
    global entitiesResV
    entitiesResV = tk.IntVar()
    global citiesListBox
    citiesListBox = tk.IntVar()
    global doStemmingV
    doStemmingV = tk.IntVar()

def makeTry():
    print('partB_support.makeTry')
    print(doStemmingV.get())
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import partB
    partB.vp_start_gui()




