#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Dec 20, 2018 01:38:15 PM +0200  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 30 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m96" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 733x488+413+174
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1031
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Engine!"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#dcef62} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text {Engine - part B} 
    vTcl:DefineAlias "$top.lab43" "TitleLable" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab45 \
        -font TkDefaultFont -foreground black -text {Source path:} \
        -background {#d9d9d9} -height 55 -width 320 
    vTcl:DefineAlias "$top.lab45" "Labelframe_srcPath" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab45
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu53 \
        -takefocus {} -text Browse 
    vTcl:DefineAlias "$site_3_0.tBu53" "browseCorpusButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 230 -y 20 -anchor nw -bordermode ignore 
    entry $top.ent46 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable corpusTextField 
    vTcl:DefineAlias "$top.ent46" "corpusPathTextField" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab48 \
        -font TkDefaultFont -foreground black -text {Saving path:} \
        -background {#d9d9d9} -height 55 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 320 
    vTcl:DefineAlias "$top.lab48" "Labelframe_posting" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu57 \
        -takefocus {} -text Browse 
    vTcl:DefineAlias "$site_3_0.tBu57" "browsePostingButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu57 \
        -in $site_3_0 -x 230 -y 20 -width 76 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    entry $top.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable postingTextField 
    vTcl:DefineAlias "$top.ent49" "postingPathTextField" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu58 \
        -takefocus {} -text {Reset All} 
    vTcl:DefineAlias "$top.tBu58" "resetAllButton" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu60 \
        -takefocus {} -text {All Terms} 
    vTcl:DefineAlias "$top.tBu60" "allTermsButton" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu61 \
        -command makeTry -takefocus {} -text {Show Dictonary} 
    vTcl:DefineAlias "$top.tBu61" "showDictButton" vTcl:WidgetProc "Toplevel1" 1
    button $top.but62 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Generate Engine} -textvariable generateButton 
    vTcl:DefineAlias "$top.but62" "generateEngineButton" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab66 \
        -font TkDefaultFont -foreground black -text {Query Field} \
        -background {#d9d9d9} -height 175 -width 690 
    vTcl:DefineAlias "$top.lab66" "Labelframe_queryField" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab66
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu69 \
        -takefocus {} -text {Search Query} 
    vTcl:DefineAlias "$site_3_0.tBu69" "singleQuerySearchButton" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn71 \
        -font TkTextFont -textvariable multiQueryTextField -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn71" "multiQueryTextField" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn72 \
        -font TkTextFont -textvariable singleQuertTextField -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn72" "singleQueryTextField" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu73 \
        -takefocus {} -text {browse Queries file} 
    vTcl:DefineAlias "$site_3_0.tBu73" "browseMultiQueryButton" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu74 \
        -takefocus {} -text {Search Queries} 
    vTcl:DefineAlias "$site_3_0.tBu74" "multiQuerySeachButton" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa75 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {List of cities:} 
    vTcl:DefineAlias "$site_3_0.tLa75" "CitiesLable" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_3_0.tCh84 \
        -variable citiesOnlyResV -takefocus {} \
        -text {Show results only from selected Cities} 
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_3_0.tCh90 \
        -variable semanticV -takefocus {} -text {Semantic Search?} 
    vTcl:DefineAlias "$site_3_0.tCh90" "semanticCheckBox" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_3_0.tCh92 \
        -variable entitiesResV -takefocus {} \
        -text {Show entitieses in results} 
    vTcl:DefineAlias "$site_3_0.tCh92" "entitiesCheckBox" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu69 \
        -in $site_3_0 -x 350 -y 30 -width 110 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn71 \
        -in $site_3_0 -x 10 -y 60 -width 196 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn72 \
        -in $site_3_0 -x 10 -y 30 -width 316 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu73 \
        -in $site_3_0 -x 220 -y 60 -width 117 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu74 \
        -in $site_3_0 -x 350 -y 60 -width 108 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa75 \
        -in $site_3_0 -x 500 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.tCh84 \
        -in $site_3_0 -x 10 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.tCh90 \
        -in $site_3_0 -x 10 -y 100 -width 222 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCh92 \
        -in $site_3_0 -x 10 -y 140 -width 181 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    listbox $top.lis83 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 122 -width 174 \
        -listvariable citiesListBox 
    .top42.lis83 configure -font TkFixedFont
    .top42.lis83 insert end text
    vTcl:DefineAlias "$top.lis83" "citiesList" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab88 \
        -font TkDefaultFont -foreground black -text Results: \
        -background {#d9d9d9} -height 215 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 340 
    vTcl:DefineAlias "$top.lab88" "Labelframe_results" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab88
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu91 \
        -takefocus {} -text {Save results} 
    vTcl:DefineAlias "$site_3_0.tBu91" "saveResultsButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu91 \
        -in $site_3_0 -x 250 -y 20 -anchor nw -bordermode ignore 
    checkbutton $top.che94 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Stemming? -variable doStemmingV 
    vTcl:DefineAlias "$top.che94" "StemmingCheckBox" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m96
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 10 -width 284 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 20 -y 70 -width 320 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 30 -y 90 -width 214 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 20 -y 130 -width 320 -height 55 -anchor nw \
        -bordermode ignore 
    place $top.ent49 \
        -in $top -x 30 -y 150 -width 214 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.tBu58 \
        -in $top -x 260 -y 190 -anchor nw -bordermode ignore 
    place $top.tBu60 \
        -in $top -x 180 -y 190 -anchor nw -bordermode ignore 
    place $top.tBu61 \
        -in $top -x 180 -y 220 -width 156 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 20 -y 190 -width 131 -relwidth 0 -height 54 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 20 -y 290 -width 690 -relwidth 0 -height 175 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lis83 \
        -in $top -x 520 -y 330 -width 174 -relwidth 0 -height 122 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab88 \
        -in $top -x 370 -y 60 -width 340 -relwidth 0 -height 215 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che94 \
        -in $top -x 20 -y 250 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

